In [1]:
import numpy as np

In [2]:
mx1=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
mx2=np.ones(5)
print(mx2)

[1. 1. 1. 1. 1.]


In [5]:
mx3 =np.ones((3,4))
print(mx3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
mx4=np.ones((4,4) , dtype=bool)
print(mx4)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [15]:
mx5=np.zeros((3,5), dtype=bool)
print(mx5)

[[False False False False False]
 [False False False False False]
 [False False False False False]]


In [16]:
mx0=np.zeros((4,5), dtype=str)
print(mx0)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [17]:
em_0=np.empty((3,4))
print(em_0)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
